# Generated by Django 5.2.11 on 2026-02-11 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('election_type', models.CharField(choices=[('IRAQ', 'Iraq'), ('KRG', 'Kurdistan')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FINISHED', 'Finished')], default='ACTIVE', max_length=10)),
                ('election_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governorates', to='core.election')),
            ],
            options={
                'unique_together': {('election', 'name')},
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.governorate')),
            ],
            options={
                'unique_together': {('governorate', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='core.district')),
            ],
            options={
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ElectionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_unit_number', models.CharField(max_length=50)),
                ('election_unit_name', models.CharField(blank=True, default='', max_length=250)),
                ('election_unit_address', models.CharField(blank=True, default='', max_length=300)),
                ('stations_count', models.PositiveIntegerField(default=0)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='core.district')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.election')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.governorate')),
                ('subdistrict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='core.subdistrict')),
            ],
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_number', models.CharField(max_length=50)),
                ('candidate_name', models.CharField(max_length=250)),
                ('list_name', models.CharField(max_length=250)),
                ('list_number', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('voting_type', models.CharField(max_length=50)),
                ('voting_governorate', models.CharField(blank=True, default='', max_length=100)),
                ('station_number', models.CharField(blank=True, default='', max_length=50)),
                ('number_of_votes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.election')),
                ('election_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='core.electionunit')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.governorate')),
            ],
        ),
        migrations.AddIndex(
            model_name='electionunit',
            index=models.Index(fields=['election', 'election_unit_number'], name='core_electi_electio_557ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='electionunit',
            index=models.Index(fields=['governorate'], name='core_electi_governo_9cbe0a_idx'),
        ),
        migrations.AddIndex(
            model_name='electionunit',
            index=models.Index(fields=['district'], name='core_electi_distric_e06a20_idx'),
        ),
        migrations.AddIndex(
            model_name='electionunit',
            index=models.Index(fields=['subdistrict'], name='core_electi_subdist_5db5d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='electionunit',
            unique_together={('election', 'election_unit_number')},
        ),
        migrations.AddIndex(
            model_name='voterecord',
            index=models.Index(fields=['election', 'governorate'], name='core_votere_electio_2ce6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='voterecord',
            index=models.Index(fields=['election_unit'], name='core_votere_electio_9bfe3f_idx'),
        ),
        migrations.AddIndex(
            model_name='voterecord',
            index=models.Index(fields=['list_number'], name='core_votere_list_nu_f8c23a_idx'),
        ),
        migrations.AddIndex(
            model_name='voterecord',
            index=models.Index(fields=['voting_type'], name='core_votere_voting__d18823_idx'),
        ),
    ]
