# Generated by Django 5.2.11 on 2026-02-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voterecord',
            constraint=models.UniqueConstraint(fields=('election', 'governorate', 'election_unit', 'candidate_number', 'list_number', 'voting_type'), name='unique_vote_record'),
        ),
    ]
