# Generated by Django 5.2.11 on 2026-02-19 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_voterecord_unique_vote_record'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voterecord',
            name='unique_vote_record',
        ),
    ]
