# Generated by Django 5.2.11 on 2026-02-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
