# Generated by Django 5.2.11 on 2026-02-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionunit',
            name='total_allowed_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
